version: '3.9'
services:
  postgres_db:
    image: 'postgres:latest'
    environment:   # postgres database name and password
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
    ports:    # ports exposed for other containers to connect to
      - 5432:5432
  app:
    image: python-app
    container_name: cli
    build: .
    depends_on:
      - postgres_db



