version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
  app:
    container_name: python_app
    build: ./src
    volumes:
      - ./src/:/home/app
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:



